version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: go-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_password_123
      POSTGRES_DB: go_web_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go_user -d go_web_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
