services:
  - type: web
    name: go-web-api
    runtime: go
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: go-web-api-db
          property: connectionString
    buildCommand: go build -o main main.go
    startCommand: ./main

databases:
  - name: go-web-api-db
    region: oregon
